on:
  pull_request:
    branches:
      - main
      - rel-1877
      - sta-1877
      - rel-2150
      - sta-2150
  push:
    branches:
      - main
      - rel-1877
      - sta-1877
      - rel-2150
      - sta-2150
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    uses: gardenlinux/package-build/.github/workflows/build.yml@c721cec9a0210475a38460e2b974a2984a84f901 # main
    with:
      publish_release: ${{ github.event_name != 'pull_request' }}
      release: false
