on:
  pull_request:
    branches:
      - main
      - rel-1877
      - sta-1877
  push:
    branches:
      - main
      - rel-1877
      - sta-1877
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    uses: gardenlinux/package-build/.github/workflows/build.yml@main
    with:
      publish_release: ${{ github.event_name != 'pull_request' }}
      release: false
